Feature/acc activation
Al-Fro/rails-study-app pull request #3
Opened 2020-09-18 10:55 UTC by Al-Fro

2020-09-22 08:39 UTC, seliverstov-maxim requested changes

2020-09-22 08:39 UTC, seliverstov-maxim commented on app/controllers/account_activations_controller.rb
> +    decoded_id = Users::ActivationCode.decode(params[:encode_id])
в параметрах должен быть не encode_id а registration_token

2020-09-22 08:39 UTC, seliverstov-maxim commented on app/controllers/account_activations_controller.rb
> +    unless user && !user.activated
ужастное условие. отрицание с unless мы не используем
более одного условия с unless мы не используем

2020-09-22 08:39 UTC, seliverstov-maxim commented on app/controllers/users_controller.rb
> +    @encode_id = Users::ActivationCode.encode(@user.id)
почему генерим токен перед проверкой сохранен ли пользователь?

2020-09-22 08:39 UTC, seliverstov-maxim commented on app/services/Users/activate.rb
> +      @user.update_columns(activated: true)
почему так сделал? `update_columns`

2020-09-22 08:39 UTC, seliverstov-maxim commented on config/environments/test.rb
> +  config.action_mailer.default_url_options = { :host => 'localhost:3000' }
`{host: '...'}`

2020-09-22 08:39 UTC, seliverstov-maxim commented on test/mailers/user_mailer_test.rb
> +    assert email.body.to_s.include?("Hi, #{user.name}!")
уж лучше бы проверял на наличие `registration_token` чем на "Hi, username"

2020-09-22 08:39 UTC, seliverstov-maxim commented on test/services/users/activation_code_test.rb
> +    code = Users::ActivationCode.encode('foo')
Я тут подумал. Кажется `ActivationKey` звучить лучше чем `ActivationCode`

2020-09-22 08:39 UTC, seliverstov-maxim commented on test/services/users/activation_code_test.rb
> +    code = Users::ActivationCode.encode('foo')
мб Валя что подскажет. в целом придирка.

2020-09-23 08:39 UTC, Al-Fro commented on app/controllers/account_activations_controller.rb
> +    decoded_id = Users::ActivationCode.decode(params[:encode_id])
наверное, activation_token?

2020-09-23 09:35 UTC, seliverstov-maxim requested changes

2020-09-23 09:35 UTC, seliverstov-maxim commented on app/controllers/users_controller.rb
> +    @encode_id = JwtService.encode('activation_key', @user.id)
`encoded_id`

2020-09-23 09:35 UTC, seliverstov-maxim commented on app/controllers/users_controller.rb
> +    UserMailer.with(user: @user, encode_id: @encode_id).user_activation.deliver_now
асинхронную отправку потом будешь делать? в другом пр?

2020-09-23 09:35 UTC, seliverstov-maxim commented on app/mailers/user_mailer.rb
> +    mail(to: @user.email, subject: 'Please, activate account')
локали

2020-09-23 09:35 UTC, seliverstov-maxim commented on app/services/users/activate.rb
> +      @user.update!(activated: true)
мы как-то обрабатываем исключение если `update` что-то выкинет? или это нарочно так и задумано?

2020-09-23 09:58 UTC, Al-Fro commented on app/controllers/users_controller.rb
> +    UserMailer.with(user: @user, encode_id: @encode_id).user_activation.deliver_now
да, уже подготовлен, ждет очереди

2020-09-28 08:26 UTC, seliverstov-maxim commented
👍

2020-09-28 08:27 UTC, merged